--
-- Création des tables de l'article de configuration CSCI_GLOB
--

PROMPT Creating Table 'CG_REF_CODES'
CREATE TABLE CG_REF_CODES
 (RV_DOMAIN VARCHAR2(100) NOT NULL
 ,RV_LOW_VALUE VARCHAR2(240) NOT NULL
 ,RV_HIGH_VALUE VARCHAR2(240)
 ,RV_ABBREVIATION VARCHAR2(240)
 ,RV_MEANING VARCHAR2(240)
 )
/

